### ISSUE TITLE
Kernel path settings

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/MyST-NB#11]
Notebooks being executed often require external assets: importing scripts/data/etc. These are prepared by the users.

At the same time, the notebook files will likely be generated during the build process, and not executed by the user directly. It's working directory will be defined by the kernel creation parameters.

Therefore, I think, it is a worthy point to discuss: how will the users access external assets from their executable code?

**Comment by chrisjsewell** [comment]
I htink this is closed with https://myst-nb.readthedocs.io/en/latest/use/execute.html#executing-in-temporary-folders, but feel free to re-open

**Comment by chrisjsewell** [comment]
yeh good point 👍

**Comment by chrisjsewell** [comment]
fixed 👌

**Comment by akhmerov** [comment]
What about the thebe/binder question?

**Comment by chrisjsewell** [comment]
I 99% pretty sure Binder opens the notebook in its directory, haven't played around much with Thebe  yet though, but I will bear it in mind

**Comment by akhmerov** [comment]
Awesome, thanks.
