### ISSUE TITLE
Add support for CellNodes to latexpdf

### ISSUE THREAD

**Issue by mmcky** [executablebooks/MyST-NB#137]
**Describe the solution you'd like**

We need to add support for `code-cell` directive for the default `latex` and `latexpdf` writer. 

**Additional context**

These methods can also be used when constructing a custom LaTeX `translator` in the future that will generate more readable / editable `tex` (which uses `minted` code environments etc.)

**Comment by mmcky** [comment]
@chrisjsewell @choldgraf are there generic functions for working with the various `mime` types available? Can't remember where we ended up on this.

**Comment by choldgraf** [comment]
wouldn't these not make it into the Sphinx doctree, though? Anything with `{code-cell}` in it should be converted to `ipynb` before being parsed I believe...

**Comment by chrisjsewell** [comment]
Yes `code-cell` should never be "seen" by sphinx, perhaps you are thinking of the AST objects? like

```xml
        <CellNode cell_type="code" classes="cell">
            <CellInputNode classes="cell_input">
            <CellOutputNode classes="cell_output">
                <CellOutputBundleNode outputs="1">
```

**Comment by mmcky** [comment]
@chrisjsewell indeed -- I am thinking of the `ast` objects that we have added to support `Cells`. @AakashGfude and I would like to add support for these `node types` for the generic latex writer. Is there documentation about the names of these `nodes` in the `ast`?

**Comment by mmcky** [comment]
So we will need `visit` and `depart` methods for:

1. `CellNode`
1. `CellInputNode`
1. `CellOutputNode`
1. `CellOutputBundleNode`

**Comment by mmcky** [comment]
ok so this `transform` is applied on the outputs:

https://github.com/ExecutableBookProject/MyST-NB/blob/master/myst_nb/transform.py

**Comment by chrisjsewell** [comment]
I would look at https://github.com/ExecutableBookProject/MyST-NB/blob/f31f9b53595aef03fce32ca0577147414b046c54/tests/test_transform.py#L1

and the test outputs in https://github.com/ExecutableBookProject/MyST-NB/tree/master/tests/test_transform, which provide an example of the final AST which a translator would "see"

**Comment by chrisjsewell** [comment]
Can this be closed @mmcky?

**Comment by mmcky** [comment]
@chrisjsewell given our current focus is on supporting `LaTeX` builds via the generic sphinx `latexpdf` builder coupled with `LaTeX` theme support this can be closed for now. We will try and avoid writing our own `translator` in the short term.
