### ISSUE TITLE
Execution timeout

### ISSUE THREAD

**Issue by AakashGfude** [executablebooks/MyST-NB#139]
While running build for https://github.com/ExecutableBookProject/quantecon-example , `parallelization.md` file, times out in my system

![image](https://user-images.githubusercontent.com/6542997/78621299-a5933580-78c5-11ea-8a01-a39b4b9a79eb.png)

Will pass a timeout argument to configure, to ExecutePreProcessor of `jupyter-cache` to fix this.

**Comment by choldgraf** [comment]
Hey @AakashGfude - any updates on conversations you've had in the nbformat repo about where to put metadata?

**Comment by AakashGfude** [comment]
Hey @choldgraf , so, in this discussion thread https://github.com/jupyter/nbclient/issues/45, it was mentioned that the proposed format will be discussed with the developers of `nbformat` in an issue. I will check back on this.

**Comment by choldgraf** [comment]
Sounds good - I think you are both waiting for one another to open up this issue. Can you try it? Or if you don't want to I can open the issue

**Comment by AakashGfude** [comment]
@choldgraf  thanks. No worries, I will open an issue then.
