### ISSUE TITLE
Page Level and Project Level PDF Constructors (Latex Writers)

### ISSUE THREAD

**Issue by mmcky** [executablebooks/MyST-NB#145]
**Describe the solution you'd like**

Currently the standard `latexpdf` writer in sphinx will construct a `project` level `pdf` file (i.e. a single PDF for the whole project). However in our experience you also want the ability to make `page`/`document` level `pdf` files to allow downloads on a more micro scale (when creating a `website`. For `quantecon` projects our `latex` writer builds both a `project` and `document` level pdf. 

**Additional context**

This can be a feature implemented as part of a custom LaTeX writer.

**Comment by chrisjsewell** [comment]
@mmcky can this be closed here? (since its not myst-nb specific)

**Comment by mmcky** [comment]
This will be closed by https://github.com/executablebooks/jupyter-book/pull/687 so this can be closed.
