### ISSUE TITLE
InlineNodes don't work with headers

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#170]
I just tried building a book that uses `{glue:}` in the header of the page, and got this error:

```
NotImplementedError: <class 'sphinx.transforms.SphinxContentsFilter'> visiting unknown node type: PasteInlineNode
```

Do we want to support `{glue:}` roles in headers?

If so, this is a bug and we should fix / test it
If not, this is a docs update issue

**Comment by chrisjsewell** [comment]
>  is there some magic going on somewhere such that docutils knows about these nodes without use registering them?

I think this is because these nodes are generally picked up before and Visitor parses, since they should have already been transformed by:
https://github.com/executablebooks/MyST-NB/blob/50fd0b373280321aa869bcfbc1d861aa45d03bcf/myst_nb/nb_glue/transform.py#L17

**Comment by choldgraf** [comment]
@chrisjsewell check the latest version of the issue text - I realized that there was a more specific issue than the nodes not being recognized

**Comment by chrisjsewell** [comment]
This is the transform in question: https://github.com/sphinx-doc/sphinx/blob/62711bc081744cecba2af799ad8dbf678f6a97a4/sphinx/transforms/__init__.py#L308, which subclasses https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/transforms/parts.py#L70.

It has a priority of 720, which is higher than the glue transform (699), so I guess in our tests we just don't call any with such a high priority.

But yes we should register this then.

**Comment by chrisjsewell** [comment]
I think you should be able to register it as part of the domain class: https://github.com/executablebooks/MyST-NB/blob/50fd0b373280321aa869bcfbc1d861aa45d03bcf/myst_nb/nb_glue/domain.py#L262
