### ISSUE TITLE
Remove nb.metadata.file_extension fixes when upstream PR merged

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-NB#177]
See jupyter/jupyter-sphinx#127

Then the upcoming changes in #175 and https://github.com/executablebooks/MyST-NB/blob/afba1fe9ccae394e9b13621e113ab96a5266c6fe/myst_nb/cache.py#L185-L191 can be removed

**Comment by choldgraf** [comment]
ah nice - if you get that patch in to jupyter-sphinx, I'll cut another patch release and then we can close the myst-nb PR I've got, I agree this is a better fix
