### ISSUE TITLE
MyST-NB on conda-forge

### ISSUE THREAD

**Issue by brbarkley** [executablebooks/MyST-NB#185]
Thanks for the great work so far on `myst-nb`. I recently switched from `nbsphinx` and am finding your package very useful.

**Is your feature request related to a problem? Please describe.**
I use conda to manage my projects and, though I'm no purist, I try to limit the extent to which I mix conda and pip (as I've read it can [cause problems](https://www.anaconda.com/blog/understanding-conda-and-pip)).

**Describe the solution you'd like**
I've noticed that conda-forge is the recommended means of installation for `myst-parser`. Any plans to also distribute `myst-nb` on conda-forge? Are there current barriers that keep you from distributing on conda?

If it's just a matter of doing a basic `conda skeleton` from the myst-nb pypi package and then `conda-build` (see [here](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html#building-a-simple-package-with-conda-skeleton-pypi)), I might be able to assist. Anything beyond that, I'd probably be in over my head.

**Comment by choldgraf** [comment]
I don't think there are any technical reasons we couldn't use conda-forge here as well...probably just a matter of developer time. I don't think it would be complicated but maybe @chrisjsewell could advise there?

**Comment by phaustin** [comment]
You'll also need a recipe for jupyter-sphinx, and it would be good to include the utf8 fix:  https://github.com/jupyter/jupyter-sphinx/pull/125/commits/7faaf29a97cba54d7d1cfb3914906cccaa56bbaa

**Comment by chrisjsewell** [comment]
Yeh that was the only reason, because some of the dependencies need to be added first

**Comment by chrisjsewell** [comment]
Opened https://github.com/jupyter/jupyter-sphinx/issues/148, then we can revisit

**Comment by chrisjsewell** [comment]
This is now available, but just needs documenting

**Comment by bsipocz** [comment]
conda-forge is linked in the README, it should be good enough as zeroth order documentation for a third party packager (as the official release locations are on pypi and github anyway).
