### ISSUE TITLE
Upstream the inline `cell_output_to_nodes`

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#187]
From #24 

> Note this also now needs to be up-streamed: https://github.com/ExecutableBookProject/MyST-NB/blob/4d83e8cc6668d2e8ba531ea11bc49b242d1ddcd8/myst_nb/transform.py#L66

> It is the same as `cell_output_to_nodes` but returns inline-level elements rather block-level (`literal` instead of `literal_block`, `math` instead of `math_block`, etc) and is utilised in the new glue functionality: https://myst-nb.readthedocs.io/en/latest/use/glue.html#the-glu-any-role-directive

**Comment by chrisjsewell** [comment]
Well its been removed in any case 😆
