### ISSUE TITLE
Question: How to allow errors in the code?

### ISSUE THREAD

**Issue by HTenkanen** [executablebooks/MyST-NB#190]
Hi @choldgraf!

Continuing my dive to executablebooks world.. :) 

I faced an issue relating to our teaching materials. We have a case where we basically want to demonstrate the students that certain things produce errors such as when you try to call a function/variable that has not been defined yet. Previously, we have been using `nbsphinx` to build the Sphinx pages from Notebooks, but now with the sphinx-book-theme, we'll be using MyST-NB. With the `nbsphinx` it was possible to allow errors in the codes by configuring in the `conf.py` file following: `nbsphinx_allow_errors = True`. This is how things work in nbsphinx: https://nbsphinx.readthedocs.io/en/0.7.0/allow-errors.html

Is it somehow possible to do the same with MyST-NB? (I tried to look for info but didn't find).

Currently when building the pages I get something like following:
![image](https://user-images.githubusercontent.com/6659534/83673469-9253cc00-a5cf-11ea-9ac0-84be20a854e2.png)

**Comment by HTenkanen** [comment]
Ah, well this is not necessarily a bug..sorry

**Comment by choldgraf** [comment]
just opened up a PR to show how to do this, wanna give it a shot? https://github.com/executablebooks/MyST-NB/pull/191

**Comment by HTenkanen** [comment]
@choldgraf Cool, thanks! I will try it out tomorrow and let you know how it goes :+1:

**Comment by HTenkanen** [comment]
@choldgraf Okay, was able to get it working. 👍 However, I think adding cell-tags using Jupyterlab or Jupyter Notebooks might be something that most of the users do not know how to do (including me). Hence, it might be useful to add also information about how to add tags to code cells? There isn't atm any documentation about this on the Jupyterlab docs either, but what I found useful was this issue: https://github.com/jupyterlab/jupyterlab-toc/issues/87

Additional thought: although I understand that the current behavior which forces you to specifically tag the cells with `raises-exception` might be exactly what is wanted, still I think for educational purposes this might become a bit frustrating because introducing errors in the code is quite typical thing that you do when e.g. teaching the basics of Python. I can see that it might be quite typical that you forgot to add the cell-tag, and if using e.g. CI/CD for building the docs (which we do), you end up having broken builds quite often. Hence, if possible, I think having a setting that would allow errors to happen globally within the same project would be a really nice feature. Hence, this would be something similar that is currently implemented in `nbsphinx`. What do you think?

**Comment by choldgraf** [comment]
makes sense - want to open up a new issue to discuss allowing errors across a whole notebook, or a whole book?

**Comment by HTenkanen** [comment]
@choldgraf Sure, will do 👍
