### ISSUE TITLE
Get ipywidgets working

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#192]
Now that the nbclient widgets bug has been fixed (I think), I think MyST-NB should work with widgets, but it seems that this is not the case. We currently use the `jupyter-sphinx` widgets code to insert widgets into the doctree. This is done:

* by checking if widgets are in a notebook and, if so, inserting a `jupyter_widget_state` token here: https://github.com/executablebooks/MyST-NB/blob/master/myst_nb/parser.py#L172
* That token is then rendered into a `jupyter_sphinx` `JupyterWidgetState` node here: https://github.com/executablebooks/MyST-NB/blob/master/myst_nb/parser.py#L193
  - (which seems to be the same way that `jupyter-sphinx` uses it here: https://github.com/jupyter/jupyter-sphinx/blob/3c9140939db9d683b1f036a55ae4041a6b06d195/jupyter_sphinx/execute.py#L223)
* Note that this should only work with the pre-release version of `nbclient`

When I run MyST-NB, it correctly inserts the `jupyter_widget_state` token, so it seem that the `ipynb` file *does* have widget state inside it. But, the widgets still don't show up for me, and I'm not sure why. Trying to add some context above in case others have an idea for how to debug. Maybe @akhmerov has an intuition?

**Comment by akhmerov** [comment]
I'm at a loss here. Both implementations look functionally identical. Did you check whether the resulting state object actually looks similar in the AST and whether it gets attached in the output?

**Comment by choldgraf** [comment]
Hmmm, so digging a bit more. It seems like the widget state node does make it into the doctree, but at the very beginning of the doctree:

![image](https://user-images.githubusercontent.com/1839645/84058122-9dab4c80-a96d-11ea-8730-6342099807dc.png)

This node *does not* seem to make it into the HTML. I wonder if that's because it goes before the "docinfo" node?

**Comment by chrisjsewell** [comment]
See https://github.com/executablebooks/MyST-Parser/pull/152, for an example of testing the doctree before and after post-transforms

**Comment by choldgraf** [comment]
Nice - yeah I think that the issue here is that we put the node before `docinfo`. At least, if I **append** the `WidgetStateNode` instead of **prepend** it, then the widgets show up.

@chrisjsewell and strong reason not to just append it into the doctree? That's how jupyter-sphinx handles it anyway. Otherwise, I suppose we could check whether the doctree has a `docinfo` field in it and insert it there if so, but it seems appending is simpler

**Comment by chrisjsewell** [comment]
Yeh I think that should be fine
