### ISSUE TITLE
Stop automatically setting up jupyter-sphinx?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#208]
I believe that as a carryover from before MyST-markdown notebooks existed, we were using `jupyter-sphinx` to get the `jupyter-execute` directive. I don't think we're using any functionality in `jupyter_sphinx` that is achieved through activating it as an extension (we're using the AST nodes and such, but that's used on the python side).

Is there any reason not to remove this line? It's probably adding some unnecessary complexity if not (e.g. I noticed this because the it's clashing with the name of a directive in `sphinx-thebelab`)

https://github.com/executablebooks/MyST-NB/blob/master/myst_nb/__init__.py#L190 

Let's see if it breaks any tests if we de-activate it: https://github.com/executablebooks/MyST-NB/pull/209

**Comment by chrisjsewell** [comment]
From #209 it turns out otherwise 😄
