### ISSUE TITLE
alt option for glue:figure directive

### ISSUE THREAD

**Issue by bmcfee** [executablebooks/MyST-NB#211]
**Is your feature request related to a problem? Please describe.**

glue:figure directives support image captions, but not alt text.  Captions are great, but alt text is important for screen readers and accessibility.

**Describe the solution you'd like**

Support alt text. :)

**Describe alternatives you've considered**

Several, as documented here: https://github.com/executablebooks/jupyter-book/issues/436

**Additional context**

I don't think additional context is needed here, but it might be worth thinking about how to support screen readers more generally.  I also need to find a way to improve accessibility for animations, which do not provide an "alt text" field in HTML5, but can use the tag content to give hints to screen readers.  Maybe that's out of scope for this issue, but it seems related enough to mention.

**Comment by choldgraf** [comment]
> I also need to find a way to improve accessibility for animations

perhaps we can open an issue for something like `glu:html` that would expect an HTML or JS blob (like javascript etc)? I can't tell if that's a good idea or not. @chrisjsewell WDYT?

**Comment by chrisjsewell** [comment]
>  it might be worth thinking about how to support screen readers more generally

Heya @bmcfee, I addressed this specific issue, but feel free to open another with any other accessibility suggestions thanks

**Comment by bmcfee** [comment]
Great, thanks @chrisjsewell !
