### ISSUE TITLE
MyST-NB Rendering in JupyterHub 2.x

### ISSUE THREAD

**Issue by emdupre** [executablebooks/MyST-NB#216]
**Describe the bug**
I hesitate to call this a "bug," as it's not providing the expected functionality **but** I'm unsure if that's because of the software or because of my usage.

I've created a Jupyter Book in MyST MD, [rendered here](https://emdupre.github.io/nha2020-nilearn) and [building from here](https://github.com/emdupre/nha2020-nilearn). When I download the generated .ipynb files directly in the browser from that book, they look as expected.

I've set up the book such that it can launch in the NeuroHackademy JupyterHub ([hub.neurohackademy.org](https://hub.neurohackademy.org)), [ which is configured here](https://github.com/neurohackademy/nh2020-jupyterhub/). It's running JupyterHub 2.x, and in that environment -- despite have jupytext and myst-nb installed -- the Myst-formatted markdown files render as only two cells: one for the YAML frontmatter and one for the rest of the content.

**To Reproduce**
Launch one of the [Jupyter Book sections](https://emdupre.github.io/nha2020-nilearn) on the NHA JupyterHub.
If you need access, please let me know and I'll see what I can do.

**Expected behavior**
Rendering as when downloading the notebooks, or on Binder.

**Environment (please complete the following information):**
 - JupyterHub 2.x

**Comment by chrisjsewell** [comment]
hey @emdupre this is most likely because jupytext is not recognising the notebook as myst or failing to parse it as myst, at which point it "falls back" to pasring as the default jupytext format.
Perhaps try specifically converting the notebook from myst format, and see if any errors arise, e.g. `jupytext --from myst --to ipynb yourfile.md`

Note this is something I'm hoping to improve on in https://github.com/mwouts/jupytext/issues/556

**Comment by emdupre** [comment]
Thanks for the quick response !

Running the conversion locally works (:tada:), but I'd really rather not host both the ipynb files and the md files. I'll ask to change the requirement from `jupytext` to `jupytext[myst]` and let you know how that goes !

I think I'm still a bit confused why it works in e.g. Binder with just `jupytext` as a requirement, though. I thought it might be because Binder seems to be using a 1.x version of JupyterHub, but is that unrelated ?

Thanks again !

**Comment by choldgraf** [comment]
I suspect that this is not related to JupyterHub, as I don't believe that anything the jupytext uses should be influenced by the hub infrastructure that is running the session...oftentimes the culprit here is the dependencies that are installed, so let us know how `jupytext[myst]` works!

**Comment by emdupre** [comment]
That didn't seem to work :disappointed: 

I'm leaning towards the suggestion in https://github.com/neurohackademy/nh2020-jupyterhub/pull/95#issuecomment-664705912 that it has something to do with the order of the packages, or other packages that are included [in the environment](https://github.com/neurohackademy/nh2020-jupyterhub/blob/master/deployments/hub-neurohackademy-org/image/environment.yml). Do you happen to know of any known conflicts ?

If this question is outside the scope of this repo and would be better discussed elsewhere, please let me know ! And thanks again.

**Comment by consideRatio** [comment]
The order of the packages, when using repo2docker, is not even fixed =/ I think it will be alphabetically sorted or so as an optimization to avoid rebuilding things. If we want to really enforce certain versions etc, we can do a pip install statement in the postBuild file @emdupre. I'm not sure what exactly to install there though.

**Comment by emdupre** [comment]
I just tried it again this morning, and now it seems to work 🎉✨

I'm not sure if you worked on it in the mean time, @consideRatio, or if it just took longer than expected for the image to propagate. But assuming the latter, `jupytext[myst]` was exactly it.

I can close this issue, then, but thanks for your insight and patience, here !

**Comment by consideRatio** [comment]
:tada: nice @emdupre !!!

> I'm not sure if you worked on it in the mean time, @consideRatio, or if it just took longer than expected for the image to propagate. But assuming the latter, jupytext[myst] was exactly it.

Ah yeah it takes ~10-15 minutes for it to be available after a PR is merged, and then the container needs to be restarted. This can be done from https://hub.neurohackademy.org/hub/home

Should we close this issue?

**Comment by choldgraf** [comment]
Wohoo!
