### ISSUE TITLE
NB execution can fail on ReadTheDocs

### ISSUE THREAD

**Issue by mje-nz** [executablebooks/MyST-NB#217]
**Describe the bug**
All the matplotlib figures on https://myst-nb.readthedocs.io are not rendering, along with the examples of displaying `pd.DataFrame` and `IPython.display.Math`, and the whole "Widgets and interactive outputs" notebook.

**To Reproduce**
1. Go to [https://myst-nb.readthedocs.io/en/latest/use/glue.html](https://myst-nb.readthedocs.io/en/latest/use/glue.html), [https://myst-nb.readthedocs.io/en/latest/examples/basic.html](https://myst-nb.readthedocs.io/en/latest/examples/basic.html), or [https://myst-nb.readthedocs.io/en/latest/examples/interactive.html](https://myst-nb.readthedocs.io/en/latest/examples/interactive.html).
2. Observe the missing outputs.

**Comment by chrisjsewell** [comment]
thanks @mje-nz, yes indeed some notebook executions are failing on RTD: https://readthedocs.org/projects/myst-nb/builds/11469995/
I've opened a PR above to look into fixing this #218

**Comment by chrisjsewell** [comment]
This may be part of the problem (https://github.com/executablebooks/MyST-NB/pull/218/checks?check_run_id=944445317):

```pytb
----------------------------- Captured stdout call -----------------------------
## deleted test_complex_outputs_unrun.ipynb/cells/0/outputs/0:
-  output:
-    output_type: stream
-    name: stderr
-    text:
-      Matplotlib is building the font cache; this may take a moment.
```

**Comment by choldgraf** [comment]
done! also what's your RTD handle? I tried chrisjsewell but it said that didn't exist

**Comment by chrisjsewell** [comment]
> done! also what's your RTD handle? I tried chrisjsewell but it said that didn't exist

I'm there as cjsewell, but it doesn't matter about me, the bot is our new ruler

**Comment by chrisjsewell** [comment]
FYI I enabled some versions on RTD: The plots are there in https://myst-nb.readthedocs.io/en/v0.8.3/use/hiding.html but missing in https://myst-nb.readthedocs.io/en/v0.8.4/use/hiding.html

**Comment by choldgraf** [comment]
huh this is really weird, I haven't noticed any plots missing in the jupyter book docs, which I believe use the latest myst-nb? https://jupyterbook.org/interactive/hiding.html#hide-cell-inputs

**Comment by chrisjsewell** [comment]
I'm just updating jupyter-cache first (to use nbclient), then I'll give it another try

**Comment by chrisjsewell** [comment]
Err, I solved the main bug afeb1b0c675b18ef90c63a897789f20aba1c1ae3, but there is still this RTD specific problem: https://github.com/jupyter/nbclient/issues/95

**Comment by choldgraf** [comment]
That's pretty weird... I wonder why rtd is behaving differently from the other ci/cd envs. Maybe a dependency they pre install or something?

**Comment by chrisjsewell** [comment]
Think I've found the difference: https://github.com/readthedocs/readthedocs.org/issues/7360

**Comment by chrisjsewell** [comment]
This is now fixed for our documentation 🎉
Apparently RTD was using a "larger" builder for the PR build (see readthedocs/readthedocs.org#7360).
I'm getting clarification on what the specs are for small/large builders to feed back to jupyter/nbclient#95) and if its an issue they could/should be handling.
Otherwise, I guess it might be good to document this potential issue for other RTD users.

**Comment by chrisjsewell** [comment]
This should also help https://github.com/jupyter/nbclient/issues/101, but will have to wait until 0.4.3 is released

**Comment by chrisjsewell** [comment]
nbclient 0.5 should hopefully now stop this from happening
