### ISSUE TITLE
"filter" unwanted execution outputs (e.g. stdout/stderr)

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-NB#228]
circling back around to this; so there are possibly two issues/improvements here:

The code emits two output, the first being a stdout stream which you essentially want to ignore (using a cell tag / sphinx option?)

_Originally posted by @chrisjsewell in https://github.com/executablebooks/MyST-NB/issues/183#issuecomment-673486942_

**Comment by choldgraf** [comment]
I think this is related to https://github.com/executablebooks/jupyter-book/issues/694

**Comment by akhmerov** [comment]
Wouldn't a global switch also make sense here? There are only few legit examples of stderr in books/documentation, and disabling it out of the box seems more user-friendly. See also https://github.com/jupyter/jupyter-sphinx/pull/73#issuecomment-519081816

**Comment by chrisjsewell** [comment]
Good point thanks, addd https://github.com/executablebooks/MyST-NB/issues/246
