### ISSUE TITLE
Brainstorm if / how much of this to contribute up to `jupyter-sphinx`

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#24]
It seems like there are a few major things that this repository does or will do, that jupyter-sphinx could do:

1. Refactor the output mimebundle handling to use a post-transform
2. Adds a myst-based `ipynb` reader
3. Will probably add its own directives to provide `markdown`-based structure of an ipynb file

Is any of that in-scope for `jupyter-sphinx`? I think the biggest bottleneck is that we currently depend on `myst`, which is still early-stages. But at least number 1 could be upstreamed.

## Rough list of stuff to add

- [x] Improvements to package structure (to make it easier to upstream more changes) (https://github.com/jupyter/jupyter-sphinx/pull/103)
- [ ] Improvements to AST objects and post-transform for docutils nodes (https://github.com/jupyter/jupyter-sphinx/pull/107)
- [ ] Inline outputs (https://github.com/ExecutableBookProject/MyST-NB/issues/24#issuecomment-599172976)
- [ ] Thebelab improvements so we can re-use here

Curious what @akhmerov thinks about that

**Comment by akhmerov** [comment]
I'll think more about it, but let me kickstart the discussion.

Here is the list of things that jupyter-sphinx does right now:

- define rST syntax related to jupyter execution
- define the corresponding docutils AST
- execute notebooks
- handle outputs
- render the resulting Sphinx website/PDF/ipynb
- enables thebelab/binder

I am open to changing/broadening the scope, but there's also a maintenance advantage in keeping everything modular. From that perspective 2. and 3. seem to be better in a separate project. Nr 1 is, on the other hand almost a no-brainer, I think.

Comparing to other planned functionality of the ExecutableBookProject, I'd love to generate a better ipynb representation of a docutils AST. Right now the notebooks that we serve to the users in jupyter-sphinx notebooks only contain code and outputs, but it would be great to improve on that.

**Comment by akhmerov** [comment]
Another certain goal for jupyter-sphinx is to aim at compatibility of the docutils AST and of the DOM of the resulting documentation with the ExecutableBookProject.

**Comment by choldgraf** [comment]
@akhmerov I'm thinking about whether it's a good time to upstream some stuff to `jupyter-sphinx`. What about something like:

* Creating a new submodule to handle the mimebundle -> docutils logic. Something like `jupyter_sphinx.mimebundle.py`. This would have:
  * the `cell_output_to_nodes` function
  * The Cell, CellInput, and CellOutput nodes: https://github.com/ExecutableBookProject/MyST-NB/blob/master/myst_nb/parser.py#L88-L106
  * The `CellOutputBundleNode` that would then be passed to the post-transform https://github.com/ExecutableBookProject/MyST-NB/blob/53dcbf892f44f80bc1db46c606ad39f5549bb51d/myst_nb/parser.py#L109
  * The `CellOutputToNodes` transform: https://github.com/ExecutableBookProject/MyST-NB/blob/master/myst_nb/transform.py#L30

The reason I'd like to move some stuff out of the context of "execution" is because MyST-NB will largely be about reading in static notebooks, or farming out execution to other tools (probably jupyter-cache and jupyter_sphinx). I'm suggesting the current "container" arrangement because I'd like to standardize the HTML/CSS associated with running Jupyter cells+outputs, and this seems like a reasonable structure. What do you think?

**Comment by choldgraf** [comment]
If there are improvements that need to be made to these, I'm open to that too...just wanna see what you think about it.

**Comment by akhmerov** [comment]
All makes sense, and I cannot think of anything to add at the moment.

**Comment by chrisjsewell** [comment]
Note this also needs to be upstreamed: https://github.com/ExecutableBookProject/MyST-NB/blob/4d83e8cc6668d2e8ba531ea11bc49b242d1ddcd8/myst_nb/transform.py#L66

It is the same as `cell_output_to_nodes` but returns inline-level elements rather block-level (`literal` instead of `literal_block`, `math` instead of `math_block`, etc) and is utilised in the new glue functionality: https://myst-nb.readthedocs.io/en/latest/use/glue.html#the-glu-any-role-directive

**Comment by akhmerov** [comment]
@chrisjsewell can you please open an issue in jupyter-sphinx based on your comment above? (or directly a PR :)

**Comment by akhmerov** [comment]
Also: should this issue be closed then? AFAIU, the follow-up can be decided on a case-by-case basis.

**Comment by choldgraf** [comment]
OK, I opened up #187 (wow, more than 150 issues since we opened this one) to track, and we can close this now
