### ISSUE TITLE
add config to raise error when (any) notebook execution fails

### ISSUE THREAD

**Issue by poldrack** [executablebooks/MyST-NB#248]
**Is your feature request related to a problem? Please describe.**
When I try to build my book using Github actions, there is no way to specifically cause the build to return an error when a notebook fails to execute.  The -W flag would achieve this, but it also would error out for other warnings (e.g. those about heading levels) that are not fatal.

**Describe the solution you'd like**
Either add a flag that causes `jb build` to raise an error when any of the notebooks fail to properly execute, or (preferably) change the default behavior so that the build fails whenever a notebook fails to execute.  The latter is what I would have expected.

**Comment by rossbar** [comment]
I'd just like to second this feature request. We have a very similar use-case where we're relying on sphinx+myst-nb to execute the notebooks in a CI system, and would like the CI to fail if notebook execution fails. I too initially tried the `SPHINXOPTS=-W` route, but then we get failures on other (more benign) warnings like the non-consecutive header warnings from myst-parser (executablebooks/MyST-Parser#262)

I've tried several workarounds, including the two [listed above](https://github.com/executablebooks/MyST-NB/issues/248#issuecomment-657780013) (AFAICT these only work for nitpicky mode and built-in sphinx warnings, respectively) and adding `warnings.filterwarning("ignore", "Non-consecutive heading")` to `conf.py`, but none of these has worked.

**Comment by jakevdp** [comment]
We're exploring using myst-nb in the JAX project (see https://github.com/google/jax/pull/5426), and this issue is a hard blocker: we need failed notebook executions to trigger a CI failure, otherwise we risk publishing broken code & outputs to the docs. Like other users, in our case the `-W` flag is not a viable option here; the reason is we have hundreds of warnings stemming from pre-existing formatting issues in numpy and scipy docstrings, which are automatically included in docstrings of JAX's wrapped functions.

Please let me know if you have any other suggestions for surfacing notebook execution errors to CI - thanks!

**Comment by chrisjsewell** [comment]
Thanks for the feedback, this definitely in the plans. 
Hopefully in the next week or two

**Comment by jakevdp** [comment]
Thanks!

**Comment by jakevdp** [comment]
I started working on this in #296. Feedback appreciated!

**Comment by jakevdp** [comment]
In the meantime, I've found one (quite brittle) workaround: monkeypatch the logger used in `myst_nb.execution` by adding the following to your sphinx `conf.py` file:
```python
from myst_nb import execution

class _FakeLogger:
    def __init__(self, logger):
        self._logger = logger

    def verbose(self, *args, **kwargs):
        return self._logger.verbose(*args, **kwargs)

    def info(self, *args, **kwargs):
        return self._logger.info(*args, **kwargs)

    def error(self, *args, **kwargs):
        if str(args[0]).lower().startswith("execution failed"):
            raise ValueError(args[0])
        return self._logger.error(*args, **kwargs)

execution.LOGGER = _FakeLogger(execution.LOGGER)
```
It's not pretty, but it gets the job done 😁
