### ISSUE TITLE
No break between aligned html table in notebook output and next cell

### ISSUE THREAD

**Issue by RubendeBruin** [executablebooks/MyST-NB#260]
**Describe the bug**

When a cell output contains an aligned HTML table, then the next cell in the book output is rendered next to it:

![afbeelding](https://user-images.githubusercontent.com/34062862/91546857-6a041100-e923-11ea-9ee7-c99ebcd37464.png)

**To Reproduce**

```python
html_table = """
<table align="left" border="1">
<tr><td>Single cell, single row table</td></tr>
</table>
"""

from IPython.core.display import display, HTML

display(HTML(html_table))
```

**Expected behavior**

I would expect the next cell to be shown below the table:

![afbeelding](https://user-images.githubusercontent.com/34062862/91546669-1abde080-e923-11ea-9f38-242a31ce2da5.png)

**Environment**

- Python Version 3.8
- Package versions or output of `jupyter-book --version`:
```
Jupyter Book: 0.7.4
MyST-NB: 0.8.5
Sphinx Book Theme: 0.0.35
MyST-Parser: 0.9.1
Jupyter-Cache: 0.3.0
```

- Operating System: Ubuntu 20.04 on WSL2

**Comment by bsipocz** [comment]
This works now, so I'm closing. Screenshot of the rendered output:
<img width="835" alt="Screenshot 2024-09-19 at 18 04 52" src="https://github.com/user-attachments/assets/5d44d6ae-b8c1-478e-80ca-eee0ad02b667">
