### ISSUE TITLE
docs: "outpus" should be "outputs"

### ISSUE THREAD

**Issue by zmoon** [executablebooks/MyST-NB#267]
spotted this little typo:

https://github.com/executablebooks/MyST-NB/blob/446cf0d269a0906eacc1b88b418c7bce40ee4cee/myst_nb/render_outputs.py#L1

**Comment by choldgraf** [comment]
ah yes - thanks for noticing! Want to try tackling it with a PR? I am happy to review!

**Comment by zmoon** [comment]
Sure!

**Comment by bsipocz** [comment]
This typo has been fixed at some point, so I'm closing the issue.
