### ISSUE TITLE
glue:figure not working with DataFrame

### ISSUE THREAD

**Issue by luisafuss** [executablebooks/MyST-NB#282]
**Describe the bug**
When I try to glue a DataFrame ({glue:}`df`) in a JupyterBook, the output doesn't look as expected:
![image](https://user-images.githubusercontent.com/54306427/102074733-80b47200-3e05-11eb-9bc0-9e3efcbc17c9.png)

When I instead try to use {glue:figure}`df`, it says "WARNING: Unknown interpreted text role "glue:figure"."

**To Reproduce**

1. jupyter-book create test
2. edit notebooks.ipynb and add a code cell
``` python
import pandas as pd
from myst_nb import glue

df = pd.DataFrame({"A": [1,2,3], "B":[4,5,6]})
glue("df", df, display=False)
df
```
and a markdown cell:
``` markdown
{glue:}`df`
```
3. jupyter-book build test

**Expected behavior**
Output of {glue:}`df` looks like the original DataFrame.

**Environment**
Jupyter Book: 0.8.3
MyST-NB: 0.10.1
Sphinx Book Theme: 0.0.39
MyST-Parser: 0.12.10
Jupyter-Cache: 0.4.1
NbClient: 0.5.1

**Additional context**
- Installing jupyter-book from github doesn't help (using master and new-release)
- removing display=False doesn't help
- {glue:figure}`df` doesn't help (it says "WARNING: Unknown interpreted text role "glue:figure")

**Comment by choldgraf** [comment]
Ahhh I realized what the issue is just after you opened this :-)

`{glue:figure}` is a **directive**, not a role (AKA, it exists across multiple lines, like this:

````
```{glue:figure} df
```
````

**not** like this: ` {glue:figure}`df` `

**Comment by luisafuss** [comment]
Thank you, this helped!
