### ISSUE TITLE
CSS for cell outputs is too aggressive

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#287]
This line of the outputs CSS is too aggressive

https://github.com/executablebooks/MyST-NB/blob/master/myst_nb/_static/mystnb.css#L7

The `*` is causing it to strip styling of library-specific outputs that include their own CSS, which changes behavior from the notebook environments. We should choose a less-aggressive CSS rule.

**Comment by akhmerov** [comment]
Great catch, I was also bitten by that, but wasn't sure what is the cause.
