### ISSUE TITLE
new release needed to satisfy pip resolver

### ISSUE THREAD

**Issue by phaustin** [executablebooks/MyST-NB#288]
I'm getting pinning conflicts between jupytext 1.9.1 and myst-nb related to markdown-it-py.  Installing from master as a workaround

pip install git+https://github.com/executablebooks/MyST-NB.git --upgrade  

to pick up markdown-it-py 0.6.1 works for me.

**Comment by chrisjsewell** [comment]
Thanks, but this has already been addressed https://github.com/executablebooks/MyST-NB/commit/541a1109caa4ccb302bb6b7ae9b978e028c1a177, although you should not yet be using the newest version of myst-nb or jupytext with jupytext
