### ISSUE TITLE
Problem with dependency resolution w/ myst-nb and jupytext

### ISSUE THREAD

**Issue by rossbar** [executablebooks/MyST-NB#289]
**Describe the bug**

If anything, this is likely a bug with the `pip` dependency resolver, but I wanted to raise here for visibility. Listing both `myst-nb` and `jupytext` in a `requirements.txt` file will cause pip to fail.

**To Reproduce**

Add both myst-nb and jupytext to a requirements file and try to install it w/ `pip -r` in a fresh virtual environment.

1. `echo -e "myst-nb\njupytext" > borked_requirements.txt
2. In a clean venv: `pip install -r borked_requirements.txt`

Note that you get the same behavior if you try to install jupytext and myst-nb in one step: `pip install jupytext myst-nb`.

The workaround is to install them in separate steps. This will complete, and pip raises a more informative error:

```
pip install myst-nb
pip install jupytext
...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
myst-parser 0.12.10 requires markdown-it-py~=0.5.4, but you have markdown-it-py 0.6.1 which is incompatible.
Successfully installed jupytext-1.9.1 markdown-it-py-0.6.1 mdit-py-plugins-0.2.4 toml-0.10.2
```

**Expected behavior**

Just reporting for visibility - maybe the `myst-nb` or `jupytext` version requirements could be updated to prevent this collision.

**Environment**

- Python Version [e.g. 3.7.1]: 3.9.1
- pip versions tried: 20.3.1 and 20.3.3
- Package versions:
  versions are unpinned in the requirements file, so pip tries to grab `myst-nb v0.10.1` and `jupytext v1.9.1`
- Operating System: linux

**Comment by choldgraf** [comment]
thanks for bringing this up! I believe that @chrisjsewell is nearing another release of myst-nb that should resolve this, just FYI :-)

**Comment by chrisjsewell** [comment]
done in https://github.com/executablebooks/MyST-NB/releases/tag/v0.11.0
