### ISSUE TITLE
Render tables in Markdown code outputs

### ISSUE THREAD

**Issue by updiversity** [executablebooks/MyST-NB#322]
**Describe the bug**

While the table is properly displayed in Jupyter, but as well when using nbsphinx, it is not displayed properly when using myst-nb. Actually in this case, it shows simply the input string.

Please note the option myst_commonmark_only=True was set.

**To Reproduce**

```
from IPython.display import display, Markdown
display(Markdown(
    '| name                       | description   | formula   |\n|:---------------------------|:--------------|:-------|\n| blablabla              | blablabla     | $\hat p - p$      |\n| badaboum | badaboum      | $\hat p - p$      |'
))
```

**Expected behavior**

by using myst-nb sphinx plugin, the table should be properly exported and the mathjax formulas should be properly displayed.

**Comment by chrisjsewell** [comment]
Heya, thanks for the feedback

> Please note the option myst_commonmark_only=True was set.

Just to note, tables are not actually part of the CommonMark specification and so won't be rendered with this option.
But anyhow, currently Markdown code cell outputs are hard-coded to be rendered with commonmark_only and so tables will not be rendered.
It's a known "issue", and certainly something I will be addressing in the not too distant future

**Comment by tsalo** [comment]
I believe that I just experienced this issue as well. Is there any kind of workaround in place for rendering markdown tables from code cells?

**Comment by chrisjsewell** [comment]
Heya, after #380 (release pending) you can now set `nb_render_markdown_format = "gfm"` or `nb_render_markdown_format = "myst"`, to configure how markdown outputs are rendered
