### ISSUE TITLE
Support nbconvert 6?

### ISSUE THREAD

**Issue by bollwyvl** [executablebooks/MyST-NB#325]
**Is your feature request related to a problem? Please describe.**

I'd like to be able able to use `myst-nb` with `nbconvert 6`. Ideally support could be maintained for `5.x`, but... the `nbconvert ~5.6` will start to be painful as more tools take advantage of the features provided by `nbconvert` 6. 

**Describe the solution you'd like**

- update the pin to `nbconvert >=5.6,<7`
- test against `5.x` and `6.x`
- fix the issues
- ship a version that works with both

**Describe alternatives you've considered**

- Do nothing until a key downstream wants to use features from nbconvert 6.
- require `6.x`

**Additional context**

- n/a

**Comment by choldgraf** [comment]
I seem to remember @chrisjsewell mentioning he actually wanted to remove the dependency on nbconvert but can't remember exactly.

But if the dependency is staying then yeah, seems like a good idea to me

**Comment by bollwyvl** [comment]
yerp, it's pulling it in for `strip_ansi`, which is a thin wrapper around a single regex which hasn't changed in [5 years](https://github.com/jupyter/nbconvert/blame/master/nbconvert/filters/ansi.py#L15).

So it seems unlike relaxing the pin is going to break anything, while vendoring that filter would be very reasonable in this case. However, as this pin has been holding back a lot of _other_ packages, it's difficult to anticipate what the total damage would be.

Low-effort PR incoming...

**Comment by bollwyvl** [comment]
PR up: https://github.com/executablebooks/MyST-NB/pull/326

**Comment by chrisjsewell** [comment]
Yep that's exactly why I want to removed it as a dependency 👍 I was waiting to do it in a more "substantiative" change to myst-no that I have planned. But fine to remove it now if it's holding up other packages (and we don't find any hidden issues).
