### ISSUE TITLE
Many passes with autobuild

### ISSUE THREAD

**Issue by memeplex** [executablebooks/MyST-NB#331]
**Describe the bug**

Probably not the fault of myst-nb and maybe not even a problem, but it seems suspicious to me the many times sphinx-autobuild iterates upon a single notebook change, specially because one of them is on a python file I wasn't aware of and another one on a checkpoint file. Do I need to configure autobuild to properly work with myst-nb? I wasn't able to find that in the documentation.

```
[sphinx-autobuild] Detected change: docs/_build/jupyter_execute/test.ipynb
Running Sphinx v3.5.4
loading pickled environment... done
...
[sphinx-autobuild] Detected change: docs/_build/jupyter_execute/test.py
Running Sphinx v3.5.4
loading pickled environment... done
...
[sphinx-autobuild] Detected change: docs/.ipynb_checkpoints/test-checkpoint.ipynb
Running Sphinx v3.5.4
loading pickled environment... done
```

**To Reproduce**

1. Create a basic sphinx project with an index and a barebones ipynb notebook.
2. Enable myst-nb, of course.
3. Run sphinx-autobuild on the project.
4. Make a change in the notebook and save it.
5. Observe the autobuild output log.

**Expected behavior**

Just one change is detected, not three, and the build process run once.

**Environment**

python==3.9.5
myst-nb==0.12.3
MacOS==11.3.1

> - Package versions or output of `jupyter-book --version`:

The template is wrong here, isn't it?

**Comment by memeplex** [comment]
Running `sphinx-autobuild` with

```
--ignore '/Users/carlos/Desktop/test-sphinx/docs/_build/jupyter_execute/*'
--ignore '/Users/carlos/Desktop/test-sphinx/docs/.ipynb_checkpoints/*'
```

"fixed" the problem. But I feel there is room for improvement here:

* Maybe `sphinx-autobuild` should ignore `_xxx` and `.xxx` by default?
* Also note that I had to pass an absolute path as a glob pattern. It would be more useful if relative paths were passed to [ignore.py#L12](https://github.com/executablebooks/sphinx-autobuild/blob/1eb7d7746b773f515de64f1bd83c14bccca8a1ef/src/sphinx_autobuild/ignore.py#L12), although I'm not sure how safe it is to assume that everything hangs from the same root.

Should I report this to the autobuild tracker?

**Comment by palewire** [comment]
I've encountered this same bug and nearly pulled my hair out. Would be great to have a fix!

**Comment by chrisjsewell** [comment]
Yeh I think this is something that needs to be asked in sphinx-autobuild first

**Comment by palewire** [comment]
I hear here, but there is a bug related to this repo’s config. The `jupyter_execute` subfolder created by myst-nb contains an ipynb file of rendered out myst markdown files. When sphinx-autobuild reloads, it will see those ipynb notebooks as new pages to renders, which then sparks an recursive loop of jupyter_execute folders inside jupyter_execute folders into eternity.

What might help is an option to myst-nb that lets you set the location of the jupyter_execute folder outside of the area that sphinx is monitoring, like a dot folder or a tmp folder or something.

Is there an option that allows that now?

**Comment by chrisjsewell** [comment]
> outside of the area that sphinx is monitoring

It is already outside of the area that sphinx monitors, since it is in the output directory.

As already suggested, you should open an issue on sphinx-autobuild, regarding ignoring the outdir
