### ISSUE TITLE
Patch release with nbconvert 6.* compatibility

### ISSUE THREAD

**Issue by joelostblom** [executablebooks/MyST-NB#345]
### Describe the enhancement you'd like

Currently myst-nb 0.12.3 depends on nbconvert < 6, but new jupyterlab features such as webpdf export requires nbconvert > 6. Since the main branch of myst-nb here on GH supports nbconvert > 6 already, it would be nice with a small patch release that makes is easier to install the packaged version of myst-nb / jupyter-book and the latest version of nbvonert for jupyterlab webpdf export in the same environment.

**Comment by nthiery** [comment]
That myst-nb's conda package requires nbconvert < 6 is indeed quite annoying for compatibility with
other recent software. In my case, I'd like to install sagemath and jupyter-book in the same environment
for our jupyterhub.

Thanks in advance!

**Comment by choldgraf** [comment]
@mmcky cut a release yesterday, so I think that this is now resolved!

**Comment by nthiery** [comment]
Ah ah! Excellent news. So timely for my needs :-)

Can't wait for the new release to show up on conda-forge!

https://anaconda.org/conda-forge/myst-nb

**Comment by choldgraf** [comment]
@nthiery hmm it looks like the tests aren't passing there - I have no idea how to debug conda-forge so I'm not sure how that is going to be resolved :-/

**Comment by mmcky** [comment]
honestly `conda-forge` has always been tricky on our other projects, a wonderful piece of machinery but complex. 

It looks like the issue is:

```
ModuleNotFoundError: No module named 'markdown_it.tree'
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=371080&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=415

Does this need to updated on conda-forge perhaps? cc @chrisjsewell

**Comment by chrisjsewell** [comment]
well you haven't updated any of the requirements yet: https://github.com/conda-forge/myst-nb-feedstock/pull/10/files

**Comment by mmcky** [comment]
aren't the updated from `setup.cfg`?

**Comment by mmcky** [comment]
ah I see - in the recipe 👍

**Comment by chrisjsewell** [comment]
no, the automated PRs never update the requirements
