### ISSUE TITLE
pipenv cannot resolve dependencies properly

### ISSUE THREAD

**Issue by franzhaas** [executablebooks/MyST-NB#355]
### Describe the problem

when installing jupyter-book and jupyterlab with pipenv it was impssible to find a set of versions and packages to fulfill all the requirements.

by changing setup.cfg of the jupyter-book package and using the 6be37cd66d1b7668b16a4bab385222b58f38930d commit of myst-nb this problem was solveable.

Please provide / point me to a way to install jupyter-book + jupyterlab without using a git hash as a version...

### Steps to reproduce

pyhton -m ensurepip
pip install pipenv
pipenv install jupyter-book jupyterlab

### The version of Python you're using

3.9.6 (conda)

### Your operating system

rhel

### Versions of your packages

jupyter Book      : 0.11.3
External ToC      : 0.2.3
MyST-Parser       : 0.14.0
MyST-NB           : 0.13.0
Sphinx Book Theme : 0.1.3
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.4

### Additional context

the issue becomes visible by using pipenv

pipenv install jupyter-book jupyterlab

# Resolution

This problem is not something that MyST-NB or Jupyter Book has control over. Instead, it is an issue with `pipenv` itself (since it does not have a proper dependency resolver. See https://github.com/jazzband/pip-tools/issues/1372 for some discussion of this. However, the next chain of releases in the stack will make this problem go away in the short term. In addition, see https://github.com/executablebooks/MyST-NB/issues/355#issuecomment-907656056 for a workaround that uses `pip`s resolver.

**Comment by franzhaas** [comment]
Hey,

i understand, this is not a issue of jupyter-book.

i leave here a link to the solution which in the end really helped me.

https://github.com/franzhaas/pipenv_by_pip

essentially using pip to resolve the dependencies.

I hope this is helpfull in the future

**Comment by choldgraf** [comment]
I've added a "resolution" section to the top comment and linked to @franzhaas's helpful post - thanks very much for following up!
