### ISSUE TITLE
Extension error (myst_nb.execution)

### ISSUE THREAD

**Issue by HGladiator** [executablebooks/MyST-NB#359]
### Describe the problem

```
Extension error (myst_nb.execution):
Handler <function update_execution_cache at 0x0000029FE1082EE8> for event 'env-get-outdated' threw an exception (exception: Notebook does not appear to be JSON: '\ufeff{\n "cells": [\n  {\n   "cell_typ...)
```

### Steps to reproduce

the error reproduce by `make` 

commented code, then it`s worked 

extensions = [
    '''
    # "myst_nb",
    '''
]

### The version of Python you're using

python3.7

### Your operating system

win10

**Comment by chrisjsewell** [comment]
Given the error, it appears your notebook has been saved in the utf-8-sig encoding and not the expected utf-8 encoding (see https://stack-overflow.com/a/49150749/5033292). Can you tell me how you created this notebook?

**Comment by HGladiator** [comment]
```
$ ./make.bat html
Running Sphinx v3.5.4
loading translations [zh_CN]... done
WARNING: The config value `myst_url_schemes' has type `tuple', defaults to `list'.
checking bibtex cache... out of date
parsing bibtex file E:\Wiki\handbook\source\references.bib... parsed 2 entries
myst v0.15.2: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'deflist', 'colon_fence'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=('http', 'https', 'mailto'), heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 211 source files that are out of date
updating environment: executing outdated notebooks... failed

Extension error (myst_nb.execution):
Handler <function update_execution_cache at 0x0000021C7C2370D8> for event 'env-get-outdated' threw an exception (exception: Notebook does not appear to be JSON: '\ufeff{\n "cells": [\n  {\n   "cell_typ...)

```

**Comment by choldgraf** [comment]
@HGladiator the Jupyter Notebook for this page has the wrong encoding. It needs to be utf-8, and it instead saved as `utf-8-sig`, see the link @chrisjsewell provided for more information on that issue (here it is again, the URL had a typo before https://stackoverflow.com/questions/17912307/u-ufeff-in-python-string/49150749#49150749)

**Comment by HGladiator** [comment]
the page of all Notebook  is `utf-8`, never used `utf-8-sig`

i want konw how can i find debug information or log  for you

the make run error is too short,
