### ISSUE TITLE
Deal with markdown outputs of cells

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#36]
We don't currently deal with the case that cells output markdown content, we should do so!

Would we want the markdown to become part of the top-level doctree, or would we want it to remain inside the `CellOutputNode` container it is a part of?

originally mentioned in #30

**Comment by akhmerov** [comment]
I think taking these out of the `CellOutputNode` would make the doctree too confusing.

If the appearance of the cells and outputs is easy to control (e.g. hide any extra boxes or output markers), I hope there wouldn't be a problem.

**Comment by choldgraf** [comment]
@akhmerov well I think the problem would be things like we had originally ran into in this repository. If the markdown parser finds a heading, then in the page `doctree` it will create a new section at the top level and start appending to that. So if someone output markdown that had headings in it, then the parser would normally start pulling that out of the `CellOutputNode` it's supposed to be in.

Maybe if we made the assumption: any document structure that is *generated* from a code cell should *not* be a part of the top-level doctree, then we could render that markdown into docutils nodes at transform time using a new `Document` object, and then just do `cell_output_node.children = document.children`

**Comment by chrisjsewell** [comment]
closed with https://myst-nb.readthedocs.io/en/latest/use/formatting_outputs.html#markdown
