### ISSUE TITLE
Better installation guide for people do not know about sphinx

### ISSUE THREAD

**Issue by Mauhing** [executablebooks/MyST-NB#376]
### Description / Summary

I have spent two days in a row to activate myst-nb but no luck.
I tried to make sphinx work. But the jupyter-notebook still does not support myst markdown.
I have no experience of using sphinx and I do not know how can I activate it with jupyter-notebook.
In your website https://myst-nb.readthedocs.io/en/latest/use/start.html
It mentions very little about `conf.py`, I create a `conf.py` by myself and copy and paste the extension. It does not work.
The result: https://imgur.com/a/1bgBg8n

Thank you for help.

### Value / benefit

I am trying to use juypter book to write up my course in university for the student.
But I realized a big problem that I can not resolve. That is: for me to cross-ref different sections, equations, I need to use myst.
But jupyter-notebook does not support myst. 
But I have to use jupyter-notebook to make sure the code produces the result I want. 

### Implementation details

The best way to do it is just to make a short video, Or better documentation.
Do not worry about quality as long as it works.

**Comment by chrisjsewell** [comment]
Heya, if you have never used sphinx, then I would suggest you use jupyter-book: https://jupyterbook.org/intro.html, which builds a simpler user experience on top of myst-parser and myst-nb

**Comment by Mauhing** [comment]
> Heya, if you have never used sphinx, then I would suggest you use jupyter-book: https://jupyterbook.org/intro.html, which builds a simpler user experience on top of myst-parser and myst-nb

Hi. I did. They mentioned myst.md file and ipynb file. But they did not mention about myst inside ipynb before you use jupytext to convert it back to myst-md file. If you follow there tutorial, you will found that
`jupyter-book create mynewbook/` has no myst-md part in the ipynb file. 

As you know, my problem is:
for me to cross-ref different sections, equations, I need to use myst.
But jupyter-notebook does not support myst.
But I have to use jupyter-notebook to make sure the code produces the result I want.

**Comment by Mauhing** [comment]
You can close. I find a workaround :)

**Comment by peterampazzo** [comment]
@Mauhing would you be up to share your workaround? I'm stuck making this work 😵‍💫

**Comment by chrisjsewell** [comment]
FYI, I believe you may be after https://github.com/executablebooks/jupyterlab-myst
