### ISSUE TITLE
Bad formatting output (stdout)

### ISSUE THREAD

**Issue by paugier** [executablebooks/MyST-NB#388]
### Describe the bug

I'm unhappy with the formatting for stdout. Both available renders ("default" and "inline") give bad results for some texts.

Here is an example (a text produced by `argparse`):

### Input (i.e. what it gives in Jupyter)

![Screenshot_JupyterLab (input)](https://user-images.githubusercontent.com/8842662/152349181-83a61a37-8eba-42ab-bdad-15ecfd4b0242.png)

### Output (what MyST-NB produces)

![Screenshot_documentation (output)](https://user-images.githubusercontent.com/8842662/152349187-cd0664ee-5925-49b1-bbe7-5991e44a74b2.png)

It would be nice to be able to render stdout as simple raw text (not inline). Is there a way to do that?

There are explanation on how to customise the render process https://myst-nb.readthedocs.io/en/latest/use/formatting_outputs.html#customise-the-render-process, but it seems to be quite complicated to use a custom [CellOutputRenderer](https://myst-nb.readthedocs.io/en/latest/api/render_outputs.html#myst_nb.render_outputs.CellOutputRenderer) class. It would be nice to have a mechanism to be able to change the CellOutputRenderer class in the `conf.py` file (without entry_points I guess).

### Reproduce the bug

Build a notebook with some particular stdout, for example:

```python
print("""
usage: fluidsim-restart [-h] [--t_approx T_APPROX] [--merge-missing-params]
                        [-oc] [-oi] [--new-dir-results]
                        [--add-to-t_end ADD_TO_T_END]
                        [--add-to-it_end ADD_TO_IT_END] [--t_end T_END]
                        [--it_end IT_END] [--modify-params MODIFY_PARAMS]
                        path

Restart a fluidsim simulation

positional arguments:
  path                  Path of the directory or file from which to restart

optional arguments:
  -h, --help            show this help message and exit
  --t_approx T_APPROX   Approximate time to choose the file from which to
                        restart
  --merge-missing-params
                        Can be used to load old simulations carried out with
                        an old fluidsim version.
""")
```

### List your environment

```
$ jupyter-book --version                                           
Jupyter Book      : 0.12.1
External ToC      : 0.2.3
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.1
Sphinx Book Theme : 0.1.10
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.4
```

**Comment by chrisjsewell** [comment]
You can use `nb_merge_streams = True` to merge all stdout into a single output: https://myst-nb.readthedocs.io/en/latest/use/formatting_outputs.html#group-stdout-and-stderr-into-single-streams

**Comment by chrisjsewell** [comment]
Good to hear, thanks for the feedback 😄
