### ISSUE TITLE
Remove strict version requirement for myst-parser

### ISSUE THREAD

**Issue by adamgayoso** [executablebooks/MyST-NB#397]
### Describe the problem/need and solution

Myst-nb pins the myst-parser version; however, newer myst-parser versions have useful features I want to use in my docs.

**Comment by chrisjsewell** [comment]
Heya, this is already being handled, as part of #380.
It's not as simple as un-pinning though, there are numerous changes to the mys-parser API (I know, because I author both of them 😉)

**Comment by chrisjsewell** [comment]
Heya #380 is now merged supporting the latest MyST-Parser, and there should be a new release soon
