### ISSUE TITLE
RFE: please update for latest `jupyter-cachev` and `myst-parser`

### ISSUE THREAD

**Issue by kloczek** [executablebooks/MyST-NB#407]
Yeah .. it would be good to be able use latest myst-nb with latest versions of those modules 😄 
https://github.com/executablebooks/MyST-NB/blob/e17e738f21b07ef82c98c4d12ee7ae3dfc6f4f4a/pyproject.toml#L36-L47
Latest versions: 
- `jupyter-cachev` 0.5.0
- `myst-parser` 0.17.2

**Comment by chrisjsewell** [comment]
dude this already being done

**Comment by chrisjsewell** [comment]
(#406)

**Comment by kloczek** [comment]
Ha .. you are right 😄 😋 
May I ask about ET of next release? 🤔 

Thx.
