### ISSUE TITLE
Allow a particular cell to fail without stopping the notebook execution

### ISSUE THREAD

**Issue by agoose77** [executablebooks/MyST-NB#434]
### Context

Currently we have the per-document `nb_execution_allow_errors` that prevents errors from arresting the notebook execution. 

### Proposal
It would be useful if this could be extended to allow a particular cell to fail without stopping.
The use case for this is to show an expression that is known to fail as an example of bad usage.

**Comment by chrisjsewell** [comment]
Heya, isn't this achieved by the `raises-exception` tag? https://myst-nb.readthedocs.io/en/latest/computation/execute.html#raise-errors-in-code-cells

**Comment by agoose77** [comment]
Well damn. I thought it strange that we didn't support this. :laughing:
