### ISSUE TITLE
Broken math in notebooks after recent updates

### ISSUE THREAD

**Issue by bluescarni** [executablebooks/MyST-NB#441]
### Describe the bug

Recent versions of ``myst-nb`` (or perhaps ``myst-parser``, not entirely sure) apparently broke math display for markdown cells in notebooks.

To begin with, this is my ``conf.py``:

https://github.com/bluescarni/heyoka.py/blob/main/doc/conf.py

I am including in the docs several notebooks which contain math enclosed either in ``$`` or ``$$`` within markdown cells. See here for one such example:

https://github.com/bluescarni/heyoka.py/blob/main/doc/notebooks/Batch%20mode%20overview.ipynb

With older versions of myst-nb (I **think** <0.16), everything worked as expected. Here is an example of correct HTML for simple inline math:

https://github.com/bluescarni/heyoka.py/blob/4b13b38b0fd016204d1583552beac029553ad96a/notebooks/Batch%20mode%20overview.html#L674

When switching to the latest version of myst, the output has now become this:

https://github.com/bluescarni/heyoka.py/blob/gh-pages/notebooks/Batch%20mode%20overview.html#L672

The issue seems to be affecting only notebooks - apparently math in plain .rst files is rendered just fine.

I looked into previous reports and it seems strange that nobody reported this yet, so this might as well be some problem in my specific configuration...

### Reproduce the bug

Use current versions of myst on notebooks including math in markdown cells.

**Comment by chrisjsewell** [comment]
Heya, thanks for the report.
Could you extract out some specific "snippets" from the links you provide and post them here, that would be really helpful, e.g. what the input Markdown is, what the expected HTML is, and what the faulty HTML is

**Comment by bluescarni** [comment]
@chrisjsewell thanks for the quick reply.

I actually just managed to fix the issue by adding:

```python
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
]
```

to my ``conf.py`` (as shown in one of the myst tutorials).

I was a bit confused by this, as in previous versions apparently this was not necessary (but again, this perhaps was due to something specific to my setup).

If this looks like the correct fix to you, please feel free to close the issue (and perhaps it would be useful to document the need for extensions to be enabled in order to get the correct math output in notebooks).

**Comment by chrisjsewell** [comment]
> If this looks like the correct fix to you

Yes indeed, previously the `dollarmath` extension was enabled by default, but that is no longer the case

**Comment by bluescarni** [comment]
> > If this looks like the correct fix to you
> 
> Yes indeed, previously the `dollarmath` extension was enabled by default, but that is no longer the case

Cheers, I'll be closing the report then.

**Comment by chrisjsewell** [comment]
Yeh no worries, obviously feel free to suggest any improvements to the documentation 😄
