### ISSUE TITLE
Support internal notebook links

### ISSUE THREAD

**Issue by sammorley-short** [executablebooks/MyST-NB#445]
### Describe the bug

**context**
When I write a jupyter notebook, I often want to make use of internal links to reference section headers within other parts of the notebook. For example if I add markdown cell with the markdown title header `# Foo`, then I can hyperlink it elsewhere in the notebook via `[Go to foo](#Foo)`.

**expectation**
When I render such a notebook using `myst-nb`, I would expect the links to persist.

**bug**
But instead this doesn't happen.

I believe this is because the `myst_heading_slug_func` slugger function is set to the [github slugger](https://github.com/Flet/github-slugger), and so the heading `# Foo` is mapped to `foo`, and so the link fails to associate, producing the error message `WARNING: 'myst' reference target not found: #Foo`.

Alternatively, if I lowercase all the links in the jupyter notebook markdown, then the links no longer work in the notebook, but now work as expected in the `myst-nb`-rendered page, providing support for the above explanation.

**problem**
This is a problem for those who write very large notebooks, for which internal links are incredibly useful.

### Reproduce the bug

1. Create a notebook with a markdown cell with the header `# Foo`
2. Create a second markdown cell with the link `[Go to foo](#Foo)`
3. Execute both cells and confirm the notebook link works.
4. Render the notebook using `myst-nb` (observe error message `WARNING: 'myst' reference target not found: #Foo`)
5. Open the resultant page, see that link is not highlighted or clickable.

### List your environment

Running python `3.10.5` on OSX Monteray, with docs built using `sphinx-build` using the `myst-nb` extension.

**Comment by chrisjsewell** [comment]
Heya, why not just set the `myst_heading_slug_func` to your desired function?

**Comment by sammorley-short** [comment]
Hey Chris. Sure, could do, but would this not potentially break other links that do conform the github convention? Also, since the capitalised method is what's supported inside Jupyter notebooks, would it not make sense to have said custom heading slug function run on all notebooks evaluated by `myst-nb` to ensure consistency?

**Comment by chrisjsewell** [comment]
> since the capitalised method is what's supported inside Jupyter notebooks

Unfortunately, this is entirely dependent on the editor that you are using to view the notebooks, for example, if I open a notebook in VS Code, then the GitHub slugs work.

**Comment by sammorley-short** [comment]
Ah, ok. I didn't appreciate this—apologies. Seems like both firefox and chrome aren't so permissive.

Out of interest, are you also able to reproduce the issue in a browser-based notebook viewer?

**Comment by chrisjsewell** [comment]
It's not specific to a browser, just depends on what (javascript) package is being used for the markdown parser on a particular site/app, i.e. what is specifically generating the HTML. Because there is not a concrete standard for the slugs, they can vary anywhere (GitHub being the closest to a standard)

**Comment by sammorley-short** [comment]
I see. How very frustrating! I guess a custom slugger will have to do then. Thanks!
