### ISSUE TITLE
Readthedocs - Executing notebook failed: CellExecutionError [mystnb.exec]

### ISSUE THREAD

**Issue by znstrider** [executablebooks/MyST-NB#457]
### Describe the bug

My readthedocs build using myst-nb fails for some notebooks. It shows a ModuleNotFoundError for the package that my docs are built for. Not sure this is actually a myst-nb thing.

```console
ModuleNotFoundError: No module named 'plottable'
```
You can have a look at the notebook output [here](https://plottable.readthedocs.io/en/latest/example_notebooks/basic_example.html)

This is the error message from the readthedocs build.

```console
/home/docs/checkouts/readthedocs.org/user_builds/plottable/checkouts/latest/docs/example_notebooks/basic_example.ipynb:
WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
```

### Reproduce the bug

I don't have a reproducible example.

**Comment by chrisjsewell** [comment]
Heya, yeh you need to configure readthedocs to install your package (and also probably to `fail_on_warning`) : https://docs.readthedocs.io/en/latest/config-file/index.html

**Comment by znstrider** [comment]
Ah, got it, thanks!
