### ISSUE TITLE
allow for sphinx 6.0

### ISSUE THREAD

**Issue by nicoa** [executablebooks/MyST-NB#466]
### Context

A new sphinx version was released and the tests in https://github.com/pydata/pydata-sphinx-theme/pull/1097 are still using the old one as they rely on myst-nb. 

Not sure if I see all consequences here, please let me know in case allowing 6.0 needs more testing of this tooling to avoid breaking anything or if you are happy to receive a PR for allowing.

**Comment by danyeaw** [comment]
MyST-Parser now support Sphinx 6.0, is the time right to update MyST-NB as well?

**Comment by OriolAbril** [comment]
This can be closed now
