### ISSUE TITLE
Bump version MyST-parser // Sphinx >= 6

### ISSUE THREAD

**Issue by miili** [executablebooks/MyST-NB#493]
### Describe the bug

It is time to upgrade to Sphinx >= 6. 👋🏻 

### Reproduce the bug

Add conflicting project dependencies 💥 

```toml
[project.optional-dependencies]
docs = [
  "myst-nb>=0.17.1",
  "sphinx>=6.1.3", # <-- Banger
  "semver>=3.0.0",
  "furo>=2023.3.27",
  "sphinx-copybutton>=0.5.1",
  "sphinx-design>=0.4.1",
]
```

**Comment by tupui** [comment]
And Sphinx 7 is just out.

**Comment by rossbar** [comment]
> Hi folks wave Are there any reasons for the upper pins in the dependencies? We recently added this package to SciPy's doc and it's limiting us.

I'd like to second this - NetworkX would like to adopt `myst-nb` into our main docs - see networkx/networkx#5221 (we already use myst-nb extensively in [nx-guides](https://github.com/networkx/nx-guides)). The primary issue we're running into is related to the upper bound pins. FWIW I've tested the NX doc builds locally with both sphinx 6 and sphinx 7 with myst-nb 0.17.2 and had no problems, so at least for this single case the pins are overly conservative.

I know this has been discussed elsewhere in the past (maybe in the executablebooks/meta repo?) and I also realize a local test from a single downstream consumer is not something that should dictate policy :upside_down_face:. I just want to provide another data point!

**Comment by LecrisUT** [comment]
:+1: instead of having upper pins in the `pyproject.toml`, just run CIs  on all major releases, then pin the version when errors are detected. Especially as dependabot PRs are not being merged or addressed.

The pinning in the `[testing]` dependencies is just hell to detangle

**Comment by mforbes** [comment]
I have been having similar issues.  I recommend reading Henry Schreiner's post about why upper-bound version constraints should be used very sparingly, and only when really needed.
* [Should You Use Upper Bound Version Constraints?](https://iscinumpy.dev/post/bound-version-constraints/)

**Comment by tupui** [comment]
@chrisjsewell do you have time to have a look into this issue? Seems like a few folks are blocked.

**Comment by LecrisUT** [comment]
See https://github.com/executablebooks/MyST-NB/pull/479#issuecomment-1589663247. I think another maintainer is needed 
@choldgraf, @Yoshanuikabundi, @aleivag have done some work detangling and addressing the tests. It would be great if their PRs can get merged, then #524 would address that issue together with #479.

**Comment by OriolAbril** [comment]
This can be closed now

**Comment by bsipocz** [comment]
Dependencies don't have upper pins any more, and I'm working on removing the remaining ones from the test/docs extras, too.
