### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by PhilipVinc** [executablebooks/MyST-NB#530]
### Describe the bug

Can you tag a new release? You've recently relaxed version constraints but those are not in a pypi released version, that still declares incompatibility with sphinx 6

### Reproduce the bug

...

### List your environment

...

**Comment by PhilipVinc** [comment]
cc @choldgraf  ?

**Comment by vyasr** [comment]
Any updates on this? Would be great to get those constraints removed if possible! Looks like all the changes have already been made and the package just needs a new tagged release for PyPI/conda-forge.

**Comment by michaelweinold** [comment]
We would greatly appreciate a new release in the near future 🙏 - this would close https://github.com/executablebooks/MyST-NB/issues/466 and https://github.com/executablebooks/MyST-NB/issues/493 and allow us to move to Sphinx 7 (and away from `nbsphinx`).

**Comment by sitic** [comment]
Can be closed, `v1.0.0` has been released and is on PyPi.
