### ISSUE TITLE
Plotly example seems broken

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/MyST-NB#54]
I see

![image](https://user-images.githubusercontent.com/2069677/76154122-40d29880-60d7-11ea-9430-1b17a17fa891.png)

On this page: https://myst-nb.readthedocs.io/en/latest/use/interactive.html

**Comment by choldgraf** [comment]
Ah yeah - I ran into the same issue locally. I think there is probably some kind of optimal javascript backend loading we can do, but I'm still not sure how to properly balance against all of these interactive JS libraries...

**Comment by choldgraf** [comment]
(FWIW it's the same for Bokeh as well)

**Comment by chrisjsewell** [comment]
I believe this is fixed now

**Comment by basnijholt** [comment]
Sorry to dredge up this old issue, however, I see the exact same issue for https://github.com/python-adaptive/adaptive/pull/355.

See this error here https://adaptive--355.org.readthedocs.build/en/355/tutorial/tutorial.LearnerND.html

@chrisjsewell, you mentioned that it's fixed. Any idea what fixed it?

**Comment by basnijholt** [comment]
I noticed that when I move the
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>
```
line from the bottom of the HTML page to the top, that the plot does work.

**Comment by basnijholt** [comment]
Sorry for the noise.

For anyone that is curious, I fixed it with https://github.com/python-adaptive/adaptive/pull/355/commits/17c26d6070a1bc7b733bccf1714631c020cee8e6.
