### ISSUE TITLE
could you make a release ?

### ISSUE THREAD

**Issue by 12rambau** [executablebooks/MyST-NB#543]
V0.17.2 is still blocked on Sphinx<6 making many pipelines (including pydata-sphinx-theme) crash

**Comment by agoose77** [comment]
We're working through some parts of the CI pipeline, and one these are fixed, we'll make a release!

**Comment by cisaacstern** [comment]
> V0.17.2 is still blocked on Sphinx<6 making many pipelines (including pydata-sphinx-theme) crash

+1 on this exact issue. Trying to update our Pangeo Forge docs in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/610 is also blocked by this. Will very much appreciate a release as soon as you are able. 🙏

**Comment by cisaacstern** [comment]
> We're working through some parts of the CI pipeline, and one these are fixed, we'll make a release!

@agoose77 is there an open Issue or PR for this? Would be curious to see if there's some way I can assist, or at least follow along with the progress.

**Comment by peytondmurray** [comment]
I'd really like to help out in any way I can to push this issue forward, but I'd really like to avoid spamming the maintainers in the process. It looks like the one remaining issue here is a typo that is aggravating pre-commit:

![image](https://github.com/executablebooks/MyST-NB/assets/14017872/a0bb1b41-c85e-490a-a567-6797721f38c3)

Normally I'd prefer not to make PRs related to this kind of thing but seeing as how it is holding up a release. But I'd be happy to do so here if it means we can get a release out.

**Comment by agoose77** [comment]
My bandwidth is pretty tied up this week. AFAICR, we're just needing to fix-up some type hints, and then we're good to go.

**Comment by peytondmurray** [comment]
Sounds good - if you point me in the direction of a specific issue, I can take care of it, though it looks like mypy is currently passing. I'd be happy to include the fix for the typo above in whatever else needs to be done.

**Comment by PhilipVinc** [comment]
@agoose77 I think the repo's ready for a new release now. Could you tag 0.18?

**Comment by njzjz** [comment]
If 0.18.0 is not available, can you tag 0.18.0b0?

**Comment by sphuber** [comment]
A new release would be great as it would also loosen the requirement on `myst-parser` to `>=0.18.0` which is necessary to be able to install `2.0.0` which is required for compatibility with Python 3.12

**Comment by agoose77** [comment]
Hi all - could you try out https://pypi.org/project/myst-nb/1.0.0rc0/?

**Comment by sphuber** [comment]
Works for our build of [AiiDA](https://aiida-core.readthedocs.io/en/latest/) :+1: thanks a lot!

**Comment by cisaacstern** [comment]
Thanks @agoose77! LGTM over in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/641 👍

**Comment by PhilipVinc** [comment]
@agoose77 I tested the `rc0` on our documentation of `https://readthedocs.org/projects/netket/`and it works great. We're just waiting for an official release of `1.0.0` to update our infrastructure.

**Comment by jakevdp** [comment]
I tested `rc0` on the documentation build for http://github.com/google/jax, and everything looks fine. Thanks for all the work on this package!

**Comment by blakeNaccarato** [comment]
Thanks for releasing v1.0.0! Looks like this issue may be able to be closed now.

It seems there isn't a changelog entry yet, but from the diff (https://github.com/executablebooks/MyST-NB/compare/v0.17.2...v1.0.0), the biggest user-facing changes seem to be Sphinx 7 support, bumping minimum `myst-parser` to 1.0, removing upper version pins in requirements, and bumping minimum Python to 3.9. Are there any other major changes to watch out for when updating? Thanks again!
