### ISSUE TITLE
GitHub Release and changelog entry for version 1.0

### ISSUE THREAD

**Issue by jtpio** [executablebooks/MyST-NB#572]
### Context

Version 1.0 seems to have been released to PyPI: https://pypi.org/project/myst-nb/1.0.0/

However there is currently no indication on the repo that version 1.0 has been released:

![image](https://github.com/executablebooks/MyST-NB/assets/591645/520b2ed7-08fe-4cc5-b094-c829866e605b)

![image](https://github.com/executablebooks/MyST-NB/assets/591645/5c2b7041-3502-456a-8091-c161e56930f7)

### Proposal

- Create a GitHub release for 1.0
- Add a changelog entry for 1.0

**Comment by agoose77** [comment]
Thanks for raising this! Will look at what's happened with the release machinery today, and fix up the changelog.

**Comment by jtpio** [comment]
Thanks @agoose77!

Yeah I noticed recent failures in https://github.com/jupyterlite/jupyterlite/pull/1256 and was wondering what could be the reason.

For now pinning `myst-nb<1` fixes the CI but we'll want to eventually remove that pin. In case you have any suggestion that would be very welcome, thanks!

**Comment by agoose77** [comment]
Fixed!
