### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by eclipseo** [executablebooks/MyST-NB#602]
Hello,

So you have had a BSD 3-Clause License file in the repo for 4 years:

https://github.com/executablebooks/MyST-NB/blob/master/LICENSE

During the rewrite 2 years ago, you specified in your pyproject.toml, that your project was MIT licensed:

https://github.com/executablebooks/MyST-NB/blob/9943ec214c35844c4535d0184f7840574fc7ab03/pyproject.toml#L17

Could you clarify which one applies?

Thanks.

**Comment by agoose77** [comment]
That's a great spot, thank you! The license has not changed, so the `pyproject.toml` content is a mistake. Thankfully, it only applies to the Trove classifiers, and not the wider metadata.

Let's fix that, and make a new release.
