### ISSUE TITLE
Pending deprecation warning in Sphinx 8

### ISSUE THREAD

**Issue by agoose77** [executablebooks/MyST-NB#645]
See CI in sphinx-book-theme

**Comment by flying-sheep** [comment]
Is it this?

> sphinx.deprecation.RemovedInSphinx10Warning: 'sphinx.util.import_object' is deprecated. Check CHANGES for Sphinx API modifications.

**Comment by bsipocz** [comment]
I'm trying to hunt down all these remaining issues. Where do you both see these? Any links to failing builds/or logs would be super useful.

**Comment by flying-sheep** [comment]
> Where do you both see these?

Code search told me https://github.com/executablebooks/MyST-NB/blob/aee9a463931a0ea6f0b49d2ec7e0776e89fdff8f/myst_nb/core/read.py#L61
