### ISSUE TITLE
Look at SoS notebooks

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-NB#87]
These are interesting: https://vatlab.github.io/sos-docs/doc/user_guide/multi_kernel_notebook.html
it means MyST-NB can support multiple languages in a single file, without having to split them up in to separate notebooks (like jupyter-sphinx does)

**Comment by choldgraf** [comment]
If I remember correctly, they basically implement their own "metakernel" that knows how to farm out execution to other kernels. It's an interesting project!

**Comment by chrisjsewell** [comment]
looked, understood
